version: '3.3'
services:
  db:
    image: influxdb:1.8
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: 'ipanema'
      DOCKER_INFLUXDB_INIT_PASSWORD: 'ipanema'
    ports:
      # <Port exposed> : < Port running inside container>
      - '8086':'8086'
    expose:
      # Opens port 3306 on the container
      - '8086'
      # Where our data will be persisted
    volumes:
      - /etc/influxdb/data:/var/lib/influxdb
      - /etc/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - /etc/localtime:/etc/localtime      
  redtracker:
    image: nodered/node-red:latest
    restart: always
    ports:
      - '1881:1880'
      - '1026:1025'
    expose:
      - '1881'
      - '1026'
    volumes:
      - nr_vol:/data2
# Names our volume
volumes:
  my-db:
  nr_vol:
