version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'mysql02'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'mysql02'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  redtracker:
    image: nodered/node-red:latest
    restart: always
    ports:
      - '1881:1880'
      - '1026:1025'
    expose:
      - '1881'
      - '1026'
    volumes:
      - nr_vol:/data2
# Names our volume
volumes:
  my-db:
  nr_vol:
